export const styles = {
  appBarStyle: { backgroundColor: "#4caf50", py: 2 },
  toolBar: { display: "flex", justifyContent: "space-between" },
  abIcon: { display: { xs: "none", md: "flex" }, mr: 1 },
  appTitle: {
    mr: 2,
    display: { xs: "none", md: "flex" },
    fontFamily: "monospace",
    fontWeight: 700,
    letterSpacing: ".3rem",
    color: "inherit",
    textDecoration: "none",
  },
  menuList: { flexGrow: 1, display: { xs: "flex", md: "none" } },
  menu: { display: { xs: "block", md: "none" } },
  appBarTitle: {
    mr: 2,
    display: { xs: "flex", md: "none" },
    flexGrow: 1,
    fontFamily: "monospace",
    fontWeight: 700,
    letterSpacing: ".3rem",
    color: "inherit",
    textDecoration: "none",
  },
  button: {
    py: { xs: 1, sm: 1.5, md: 2 },
    px: { xs: 2, sm: 2.5, md: 3 },
    border: "2px solid #fff",
    fontSize: { xs: "10px", sm: "12px", md: "14px" },
    fontWeight: 600,
    borderRadius: 2,
    minWidth: { xs: "auto", sm: 100 },
  },
};
